FROM openjdk:17
EXPOSE 8080
COPY build/libs/api-0.0.1-SNAPSHOT.jar app.jar
COPY agent.java/ agent.java/
COPY adjectives.txt adjectives.txt
COPY animals.txt animals.txt
COPY default-image.png default-image.png
COPY src/main/resources/application-local.properties application-db.properties
COPY startUp-local.sh startUp.sh
ENTRYPOINT ["./startUp.sh"]
