name: deploy
on:
  push:
    branches: ['dev']
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: make application.properties
        run: |
          cd ./src/main/resources
          touch ./application-db.properties
          echo "${{ secrets.SECRET_PROPERTIES_DEV }}" > ./application-db.properties
          echo "${{ secrets.SECRET_PROPERTIES_DEV }}" > ./application-deploy.properties
        shell: bash

        ## gradle build
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --exclude-task test

      - name: Docker build & push
        run: |
          docker build -t artique-dev -f Dockerfile .
          docker save artique-dev > artique-dev-container.tar
      - name: SCP Docker file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./artique-dev-container.tar"
          target: "/home/ubuntu/dev/"

      ## deploy to main
      #- name: Deploy to main server
      #  uses: appleboy/ssh-action@master
      #  with:
      #    host: ${{ secrets.HOST }}
      #    username: ${{ secrets.USERNAME }}
      #    key: ${{ secrets.REMOTE_SSH_KEY }}
      #    port: ${{ secrets.SSH_PORT }}
      #    script: |
      #      cd /home/ubuntu/dev
      #      sudo sh release-process.sh